"""empty message

Revision ID: 5824a5f06dd
Revises: None
Create Date: 2015-04-19 07:45:58.410077

"""

# revision identifiers, used by Alembic.
revision = '5824a5f06dd'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_entry_feed_id'), 'entry', ['feed_id'], unique=False)
    op.create_index(op.f('ix_entry_permalink'), 'entry', ['permalink'], unique=False)
    op.create_index(op.f('ix_entry_retrieved'), 'entry', ['retrieved'], unique=False)
    op.drop_index('entry_feed_id_idx', table_name='entry')
    op.drop_index('entry_permalink_idx', table_name='entry')
    op.drop_index('entry_retrieved_idx', table_name='entry')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('entry_retrieved_idx', 'entry', ['retrieved'], unique=False)
    op.create_index('entry_permalink_idx', 'entry', ['permalink'], unique=False)
    op.create_index('entry_feed_id_idx', 'entry', ['feed_id'], unique=False)
    op.drop_index(op.f('ix_entry_retrieved'), table_name='entry')
    op.drop_index(op.f('ix_entry_permalink'), table_name='entry')
    op.drop_index(op.f('ix_entry_feed_id'), table_name='entry')
    ### end Alembic commands ###
